### ISSUE TITLE
Python 3 upgrade?

### ISSUE THREAD

**Issue by redstreet** [davidcmoore/python-taxes#5]
Any interest in updating this code to python3? I call it from within a python3 environment, so it would be great. I'm happy to submit a patch. Would you be open to it?

**Comment by davidcmoore** [comment]
Yes, I'd be happy to review that PR.

**Comment by redstreet** [comment]
Great, I'll send it in a few days.

**Comment by redstreet** [comment]
PR is out: #8

**Comment by redstreet** [comment]
#9
