### ISSUE TITLE
2019 Update?

### ISSUE THREAD

**Issue by redstreet** [davidcmoore/python-taxes#6]
Is there a specific site you use to update limits, brackets, numbers etc. annually, that minimizes the update effort by perhaps simple copy-pasting? Or do you simply look at tables and manually do the update?

Either way, I'm happy to contribute a 2019 update if you're open to it.

Are you still using this code?

**Comment by davidcmoore** [comment]
I just pushed my work-in-progress for 2019 forms. I have all the federal forms done, with the caveat that 8801 and 8960 were not final on the IRS website when I last checked so they may need further work.

Also, the CA forms have not yet been updated for 2019.

**Comment by redstreet** [comment]
Terrific, thank you for sharing the updates, this is most helpful!

**Comment by redstreet** [comment]
Just checking to see if you plan to update 2018/f8801_2019.py and 2019/f8801.py? If not, I'll work on it.

**Comment by davidcmoore** [comment]
I hadn't gotten around Form 8801 yet. Yes, I'd accept a PR for those.

Note that https://www.irs.gov/pub/irs-pdf/i8801.pdf says the instructions aren't final yet for 2019, but I suspect the form itself is final.

**Comment by redstreet** [comment]
I took a stab at 8801: #10.

**Comment by redstreet** [comment]
Thanks for reviewing my form updates!

I look forward to the CA updates whenever you get around to them.
